event_payloads:

  include_h: 
    - "shared/types/BehaviourId.h"
    - "shared/types/ScreenId.h"

event_types:
  ActiveBehaviourChanged:
    - { name: oldBehaviour, type: BehaviourId }
    - { name: newBehaviour, type: BehaviourId }
  ActiveScreenChanged:
    - { name: oldScreen, type: ScreenId }
    - { name: newScreen, type: ScreenId }
