event_payloads:

  include_h: 
    - "shared/types/BehaviourId.h"
    - "shared/types/ScreenId.h"

event_types:
  ActiveBehaviourChanged:
    kind: snapshot
    fields:
      - { name: oldBehaviour, type: BehaviourId }
      - { name: newBehaviour, type: BehaviourId }
  ActiveScreenChanged:
    kind: snapshot
    fields:
      - { name: oldScreen, type: ScreenId }
      - { name: newScreen, type: ScreenId }
