states:

  ActiveBehaviour:
    include: "shared/types/BehaviourId.h"
    writer: runtime
    fields:
      - { name: behaviour, type: BehaviourId }

  ActiveScreen: 
    include: "shared/types/ScreenId.h"
    writer: runtime
    fields:
      - { name: screen, type: ScreenId }
