events:

  payloads_meta:
    include_h: 
      - "shared/types/BehaviourId.h"
      - "shared/types/ScreenId.h"

  types:

    ActiveBehaviourChanged:
      oldBehaviour: BehaviourId
      newBehaviour: BehaviourId

    RequestChangeBehaviour:
      behaviour: BehaviourId

    ActiveScreenChanged:
      oldScreen: ScreenId
      newScreen: ScreenId

    RequestChangeScreen:
      screen: ScreenId

    RequestUpdateScreens: null