### Setup ###
setup:
  app_name: Garbox # The generated runtime instance will be called NameRuntime
  initial_behaviour: CalibrationBehaviour
  tick_period_millis: 33 # ~30.3 FPS
  tick_phases: [
    { name: Heartbeat },
    { name: Input },
    { name: Logic },
    { name: Output },
    { name: Logging },
    { name: Render, delay_millis: 20 }
  ]
  stubs_prefix: "Example"
  stubs_suffix: ""

### Controllers ###
controllers:

  DisplayController:
    subdir: "hmi"
    tick_phases: Render
    receives:
      - FanStatus
      - FanSample
      - HeatpadStatus
      - HeatpadSample
      - TemperatureStatus 
      - TemperatureSample 
      - BacklightCommand 
      - ActiveBehaviourChanged
    sends: null

  DevtoolsController:
    subdir: "devtools"
    tick_phases: [Logging]
    receives: null
    sends: null

  FanController:
    subdir: "actuators"
    tick_phases: [Input, Output]
    receives: [FanCommand]
    sends: [FanStatus, FanSample]

  HeartbeatController:
    subdir: "heartbeat"
    tick_phases: [Heartbeat]
    receives: null
    sends: [Heartbeat]

  HeatpadController:
    subdir: "actuators"
    tick_phases: [Input, Output]
    receives: [HeatpadCommand]
    sends: [HeatpadStatus, HeatpadSample]

  InputController:
    subdir: "hmi"
    tick_phases: [Input]
    receives: null
    sends: [ButtonStateChanged, ButtonRepeat, EncoderStep]

  I2cPartsController:
    subdir: "sensors"
    tick_phases: [Input]
    receives: [ButtonStateChanged]
    sends: [TemperatureStatus, TemperatureSample]

### Behaviours ###
behaviours:

  CalibrationBehaviour:
    tick_phases: [Logic]
    receives: [Heartbeat, FanStatus, FanSample]
    sends: [FanCommand]

  FermentationBehaviour:
    tick_phases: [Logic]
    receives: [Heartbeat, FanStatus, FanSample, HeatpadStatus, TemperatureStatus, TemperatureSample, ButtonStateChanged, ButtonRepeat, EncoderStep]
    sends: [FanCommand, BacklightCommand, HeatpadCommand]
