# The generated runtime instance will be called NameRuntime
name: Garbox

controllers:

  DisplayController:
    ticks: [Render]
    receives: [TemperatureStatus, TemperatureSample, BacklightCommand]
    sends: null

  FanController:
    ticks: [Input, Output]
    receives: [FanCommand]
    sends: null

  HeartbeatController:
    ticks: [Heartbeat]
    receives: null
    sends: null

  HeatpadController:
    ticks: [Input, Output]
    receives: [HeatpadCommand]
    sends: null

  InputController:
    ticks: [Input]
    receives: null
    sends: null

  I2cPartsController:
    ticks: [Input]
    receives: [ButtonStateChanged]
    sends: null

initial_behaviour: FermentationBehaviour
behaviours:
  FermentationBehaviour:
    ticks: [Logic]
    receives: [Heartbeat, FanStatus, FanSample, HeatpadStatus, TemperatureStatus, TemperatureSample, ButtonStateChanged, ButtonRepeat, EncoderStep]
    sends: null
