behaviours:

  CalibrationBehaviour:
    tick_phases: [Logic]
    receive_events: [Heartbeat]
    send_events: [FanCommand]
    read_states: [FanStatus, FanSample]

  FermentationBehaviour:
    tick_phases: [Logic]

    receive_events: [
      Heartbeat, 
      RequestFermentationMode,
      RequestTargetTemperature,
      RequestFanMode
    ]
    send_events: [FanCommand, DisplayCommand, HeatpadCommand]

    write_states: [FermentationStatus]
    read_states: [FanSample, FanStatus, TemperatureSample, TemperatureStatus]
