controllers:

  DisplayController:
    subdir: "hmi"
    tick_phases: Render
    receives: [DisplayCommand]
    sends: [DisplayStatus]

  DevtoolsController:
    subdir: "devtools"
    tick_phases: [Logging]
    receives: null
    sends: null

  FanController:
    subdir: "actuators"
    tick_phases: [Input, Output]
    receives: [FanCommand]
    sends: [FanStatus, FanSample]

  HeartbeatController:
    subdir: "heartbeat"
    tick_phases: [Heartbeat]
    receives: null
    sends: [Heartbeat]

  HeatpadController:
    subdir: "actuators"
    tick_phases: [Input, Output]
    receives: [HeatpadCommand]
    sends: [HeatpadStatus, HeatpadSample]

  InputController:
    subdir: "hmi"
    tick_phases: [Input]
    receives: null
    sends: [ButtonStateChanged, ButtonRepeat, EncoderStep]

  I2cPartsController:
    subdir: "sensors"
    tick_phases: [Input]
    receives: [ButtonStateChanged]
    sends: [TemperatureStatus, TemperatureSample]

