controllers:

  DisplayController:
    subdir: "hmi"
    state: 
      - { name: Brightness, type: float }
      - { name: FramesSkipped, type: uint32_t }
    tick_phases: Render
    receives: [DisplayCommand]
    sends: null

  DevtoolsController:
    subdir: "devtools"
    tick_phases: [Logging]
    receives: null
    sends: null

  FanController:
    subdir: "actuators"
    state:
      - { name: FanState, type: FanState }
      - { name: TargetSpeed, type: float }
      - { name: RpmControl, type: bool } # Open loop (0-100%) or closed loop (RPM) control
      - { name: MeasuredRpm, type: float }
    tick_phases: [Input, Output]
    receives: [FanCommand]
    sends: null

  HeartbeatController:
    subdir: "heartbeat"
    tick_phases: [Heartbeat]
    receives: null
    sends: [Heartbeat]

  HeatpadController:
    subdir: "actuators"
    state:
      - { name: HeatpadState, type: HeatpadState }
      - { name: CurrentDuty, type: float }
      - { name: CurrentPeriod, type: uint32_t }
      - { name: NextDuty, type: float }
      - { name: NextPeriod, type: uint32_t }
      - { name: MeasuredVoltage, type: float }
      - { name: MeasuredCurrent, type: float }
      - { name: PwmProgressMicros, type: uint32_t }
    tick_phases: [Input, Output]
    receives: [HeatpadCommand]
    sends: null

  InputController:
    subdir: "hmi"
    tick_phases: [Input]
    receives: null
    sends: [ButtonStateChanged, ButtonRepeat, EncoderStep]

  I2cPartsController:
    subdir: "sensors"
    state: 
      - { name: DriverEnabled, type: bool }
      - { name: PowerEnabled, type: bool }
      - { name: Resetting, type: bool }
      - { name: HasFirstSample, type: bool }
      - { name: MeasuredTemperature, type: float }
      - { name: MeasuredHumidity, type: float }
    tick_phases: [Input]
    receives: [ButtonStateChanged]
    sends: null

