controllers:

  DisplayController:
    subdir: "hmi"
    tick_phases: Render
    receive_events: [DisplayCommand]
    write_states: [DisplayStatus, DisplayDiagnostics]

  DevtoolsController:
    subdir: "devtools"
    tick_phases: Logging

  FanController:
    subdir: "actuators"
    tick_phases: [SensorRead, ActorWrite]
    receive_events: [FanCommand]
    write_states: [FanStatus, FanSample]

  HeartbeatController:
    subdir: "heartbeat"
    tick_phases: Heartbeat
    send_events: Heartbeat

  HeatpadController:
    subdir: "actuators"
    tick_phases: [SensorRead, ActorWrite]
    receive_events: [HeatpadCommand]
    write_states: [HeatpadStatus, HeatpadSample, HeatpadProgress]

  InputController:
    subdir: "hmi"
    tick_phases: [SensorRead]
    send_events: [Button, ButtonRepeat, EncoderStep]

  I2cPartsController:
    subdir: "sensors"
    tick_phases: [SensorRead]
    write_states: [TemperatureStatus, TemperatureSample]

  TimeSeriesController:
    subdir: "hmi"
    tick_phases: [ActorWrite]
    read_states: [HeatpadStatus, TemperatureStatus, TemperatureSample, FermentationStatus]
