
event_payloads:
  include_h: [
    "app/engine/HeaterEngineState.h",
    "modules/parts/button/ButtonState.h",
    "modules/parts/fan/FanState.h",
    "modules/parts/heatpad/HeatpadState.h"
  ]

event_types:

  Heartbeat: null

  FermentationStatus:
    - Field(heaterEngineState, HeaterEngineState)
    - Field(targetTemperature, float)
    - Field(measuredTemperature, float)
    - Field(measuredHumidity, float)

  DisplayCommand:
    - Field(brightness, float)

  DisplayStatus:
    - Field(brightness, float)
    - Field(skipped, uint32_t)

  FanStatus:
    - Field(state, FanState)
    - Field(targetSpeed, float)
    - Field(rpmControlEnabled, bool) # DutyCycle or RPM (depending on rpmControlEnabled)

  FanSample:
    - Field(measuredRpm, float)

  FanCommand:
    - Field(enabled, bool)
    - Field(targetSpeed, float)
    - Field(enableRpmControl, bool) # DutyCycle or RPM (depending on enableRpmControl) 

  HeatpadStatus:
    - Field(state, HeatpadState)
    - Field(currentDutyCycle, float)
    - Field(currentPeriodMicros, uint32_t)
    - Field(nextDutyCycle, float)
    - Field(nextPeriodMicros, uint32_t)

  HeatpadSample:
    - Field(measuredVoltage, float)
    - Field(measuredCurrent, float)
    - Field(pwmProgressMicros, float)

  HeatpadCommand:
    - Field(enabled, bool)
    - Field(dutyCycle, float)
    - Field(periodMicros, uint32_t)

  TemperatureStatus:
    - Field(driverEnabled, bool)
    - Field(powerEnabled, bool)
    - Field(resetting, bool)

  TemperatureSample:
    - Field(temperatureCelcius, float)
    - Field(humidityRelative, float)

  ButtonStateChanged:
    - Field(oldState, ButtonState)
    - Field(newState, ButtonState)

  ButtonRepeat:
    - Field(count, uint32_t)
    - Field(holdTimeMicros, uint32_t)

  EncoderStep:
    - Field(steps, int32_t)
