events:

  Heartbeat:
    fields: null

  DisplayCommand:
    fields:
      - { name: brightness, type: float }

  FanCommand:
    fields:
      - { name: enabled, type: bool }
      - { name: targetSpeed, type: float }
      - { name: enableRpmControl, type: bool } # DutyCycle or RPM (depending on enableRpmControl)

  HeatpadCommand:
    fields:
      - { name: enabled, type: bool }
      - { name: dutyCycle, type: float }
      - { name: periodMicros, type: uint32_t }

  Button:
    include: "modules/parts/button/ButtonState.h"
    fields:
      - { name: oldState, type: ButtonState }
      - { name: newState, type: ButtonState }

  ButtonRepeat:
    fields:
      - { name: count, type: uint32_t }
      - { name: holdTimeMicros, type: uint32_t }
      
  EncoderStep:
    fields:
      - { name: steps, type: int32_t }

    