hardware:

  adc:
    instances:
      HeatpadVoltage: {pin: 8,  attenuation: 6,  bitWidth: 12, calibration: true}
      HeatpadCurrent: {pin: 9,  attenuation: 12, bitWidth: 12, calibration: true}

  gpio:
    instances:
      DebugGpio:      {pin: 41, mode: Disable, pull: Disable, level: 0, invert: false}
      FanEnable:      {pin: 4,  mode: Output,  pull: Disable, level: 0, invert: false}
      FanTacho:       {pin: 5,  mode: Input,   pull: Disable, level: 0, invert: false}
      I2cEnable:      {pin: 15, mode: Output,  pull: Disable, level: 1, invert: false}
      DisplayDc:      {pin: 18, mode: Output,  pull: Disable, level: 0, invert: false}
      DisplayCs:      {pin: 17, mode: Output,  pull: Disable, level: 0, invert: false}
      DisplayRst:     {pin: 10, mode: Output,  pull: Disable, level: 0, invert: false}
      HeatpadEnable:  {pin: 14, mode: Output,  pull: Disable, level: 0, invert: false}
      EncoderButton:  {pin: 1,  mode: Input,   pull: Disable, level: 0, invert: true}
      RgbLed:         {pin: 48, mode: Output,  pull: Disable, level: 0, invert: false}

  i2c:
    instances:
      I2c: {pinSda: 7, pinScl: 6, pullSda: Disable, pullScl: Disable, port: 0, frequencyHz: 100000}

  ledc:
    instances:
      timers:
        Dimming:    {id: 0, frequencyHz: 5000,  resolutionBits: 10}
        FanSpeed:   {id: 1, frequencyHz: 25000, resolutionBits: 8}
        Piezo:      {id: 2, frequencyHz: 1000,  resolutionBits: 6}
      channels:
        StatusLed0: {pin: 47, id: 0, timer: Dimming,  invert: false}
        StatusLed1: {pin: 21, id: 1, timer: Dimming,  invert: false}
        StatusLed2: {pin: 40, id: 2, timer: Dimming,  invert: false}
        StatusLed3: {pin: 39, id: 3, timer: Dimming,  invert: false}
        Backlight:  {pin: 16, id: 4, timer: Dimming,  invert: false}
        FanSpeed:   {pin: 13, id: 5, timer: FanSpeed, invert: true}
        Piezo:      {pin: 38, id: 6, timer: Piezo,    invert: false}

  spi:
    include_cpp: ["app/config/AppConfig.h"]
    instances:
      SpiDma: {
        hostDevice: SPI2_HOST, 
        pinMosi: 11, 
        pinMiso: -1, 
        pinClk: 12, 
        pinCs: -1,
        mode: 3, 
        frequencyHz: AppConfig::SpiDmaFrequencyHz,
        maxTransferSizeBytes: static_cast<int32_t>(AppConfig::SpiDmaMaxTransferSizeBytes), 
        queueSize: 5
      }

  timer:
    instances:
      FanTacho: {
        group: 0, 
        index: 0, 
        frequencyHz: 10'000'000, 
        maxValue: 0, 
        alarm_en: TIMER_ALARM_DIS, 
        counter_en: TIMER_START, 
        intr_type: TIMER_INTR_LEVEL, 
        counter_dir: TIMER_COUNT_UP, 
        auto_reload: TIMER_AUTORELOAD_EN, 
        divider: 0, 
        clk_src: TIMER_SRC_CLK_APB
      }
