screens:

  Main:
    subdir: main
    replay: true
    use_lvgl: true
    gui_filename: MainScreen.xml
    tick_phases: null
    receives: [DisplayCommand, FanCommand, HeatpadCommand]
    sends: null

  Debug:
    subdir: debug
    replay: true
    use_lvgl: true
    tick_phases: null
    receives: null
    sends: [DisplayCommand]

  EventLog:
    subdir: eventlog
    replay: false
    use_lvgl: true
    tick_phases: null
    receives: null
    receives_all: true
    sends: null